### ISSUE TITLE
根据KBEngine v0.9.16的api中关于executeRawDatabaseCommand回调函数的描述，Query中的几个回调函数参数有误。

### ISSUE THREAD

**Issue by lupurs** [acatadog/EntitySimulator#2]
executeRawDatabaseCommand的回调函数一共只有三个参数，加上functools.partial中加入的cmd, callback两个参数，一共五个。
但是Query中的几个_callback函数都是六个参数的，最后一个error落空。

**Comment by acatadog** [comment]
由于需要取得插入后的auto id，所以需要KBEngine.executeRawDatabaseCommand()返回这个参数，而官方版本并未合并这个修改，因此官方版本不能使用这个封装。
如果要使用这个封装，你可以更新我名下的KBEngine分支版本，KBEngine.executeRawDatabaseCommand()的具体参数可参考doc下的相关API文档。
