### ISSUE TITLE
请问能否增加一个通过配置自动在指定db建表的功能？

### ISSUE THREAD

**Issue by lupurs** [acatadog/EntitySimulator#3]
EntitySimulator很适合用在和实体无关的场合比如写日志等，这个时候表就只能手动创建了。不知EntitySimulator能否提供自动建表功能：）
非常感谢。

**Comment by acatadog** [comment]
我们应该充份使用KBEngine的机制，此模块的仅仅是为了辅助，所以正确使用方式应该是这样的：
任何需要自动创建的表，都应由*.def来配置——也就是说，如果我们需要一个名为SomeLog的表，那么最好的使用方式就是在entity_defs/下定义一个名为SomeLog.def的文件，并把它加入到entities.xml中，但我们并不需要实现任何的脚本，在SomeLog.def中也不需要声明任何方法，仅需要声明相关的属性作为表格字段即可。这样dbmgr在运行时会自动检测并创建相应的表，而不需要我们再做别的事情。
在这种情况下，剩下的就是使用EntitySimulator定义一个与SomeLog.def相同的格式的脚本，直接操作该表即可。
